In [1]:
import numpy as np

In [2]:
# An array is a data structure that stores numbers in rows and columns (like matrices in math).
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
## Matrix (2D Array)
matrix = np.array([[1 ,2 , 3],
                   [4, 5, 6]])
print(matrix) ## A 2D NumPy array = Matrix in math.

[[1 2 3]
 [4 5 6]]


####  Array Properties

In [ ]:
print(matrix.shape)
print(matrix.ndim)
print(matrix.size)
print(matrix.dtype) # shape = rows × columns, ndim = number of dimensions.

(2, 3)
2
6
int64


In [ ]:
## Array Creation Methods
np.zeros((3,3))
np.ones((2,2))
np.arange(1,10,2)
np.linspace(0,1,5)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [13]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.eye(3) # Identity Matrix = used in ML as the base for transformations.

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Dot Product
# Used to combine features and weights in ML:
# y = w.x = w1x1 + w2x2 + w3x3
x = np.array([1, 2, 3])
w = np.array([4, 5, 6])
dot = np.dot(x, w)
print(dot)

32


#### Array Operations

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


#### Matrix Operations

In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

print("Addition:\n", A + B)
print("Multiplication:\n", np.dot(A, B)) # Matrix multiplication = combines features and weights.
print("Transpose:\n", A.T) # Transpose = swaps rows ↔ columns.
print("Inverse:\n", np.linalg.inv(A)) #Inverse = used in solving linear equations (normal equation in Linear Regression).

Addition:
 [[3 2]
 [4 7]]
Multiplication:
 [[ 4  6]
 [10 12]]
Transpose:
 [[1 3]
 [2 4]]
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


####  Array Slicing & Indexing

In [ ]:
# Slicing helps in feature selection in datasets.
arr = np.array([[10, 20, 30],
                [40, 50, 60], # Array Slicing & Indexing
                [70, 80, 90]])

print(arr[0, 1]) # 20
print(arr[:, 1])
print(arr[1, :])     # row 1 → [40, 50, 60]
print(arr[0:2, 1:3]) # submatrix

20
[20 50 80]
[40 50 60]
[[20 30]
 [50 60]]


In [28]:
import numpy as np

# Features (X): height, weight
X = np.array([[150, 60],
              [160, 65],
              [170, 72]])

# Weights (W): learned coefficients
W = np.array([0.5, 0.8])

# Predicted output (y)
y_pred = np.dot(X, W)
print("Predicted Output:", y_pred)

Predicted Output: [123.  132.  142.6]
